#!/bin/bash
#
# Provide convinient way to install fuzzy-finder and to setup related settings.

PLATFORM=$(uname -s)
CWD=$(dirname ${BASH_SOURCE[0]})

source "${CWD}/arch/common.bash"

main()
{
  for opt in "$@"; do
    case "${opt}" in
      --d)
        export OPTION_VERBOSE=1
        ;;
      --help|*)
        usage
        exit 0
        ;;
    esac
  done

  case "${PLATFORM}" in
    Darwin)
      source "${CWD}/arch/darwin.bash"
      ;;
    Linux)
      if [ "$(os_name)" = "centos" ]; then
        source "${CWD}/arch/centos.bash"
      elif [[ "$(os_name)" = "ubuntu"  || "$(os_name)" = "Ubuntu" ]]; then
        source "${CWD}/arch/ubuntu.bash"
      else
        error "Unsupport Linux version $(os_name)"
        exit 1
      fi
      ;;
    *)
      error "Unsupport PLATFORM -> ${PLATFORM}"
      exit 1
      ;;
  esac

  banner hi
  progress install_git
  progress install_moreutils
  progress install_ag
  progress install_fzf
  progress update_bashrc
  progress update_vimrc
  progress update_tmux 
  banner bye
}

main "$@"
